use serde::Serialize;
use std::time::Duration;
use tokio::time::timeout;
use utoipa::ToSchema;

use crate::error::AppError;

const VECTORIZE_TIMEOUT: Duration = Duration::from_secs(300);

// ── Stats ─────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct VectorizeStats {
    pub input_features: usize,
    pub min_zoom: u8,
    pub max_zoom: u8,
    pub layer_name: String,
    pub size_bytes: usize,
}

// ── Main function ─────────────────────────────────────────────────────────────

/// Generate an .mbtiles vector tile package from GeoJSON bytes using tippecanoe.
/// Returns `(mbtiles_bytes, output_filename, stats)`.
pub async fn do_vectorize(
    file_bytes: &[u8],
    layer_name: &str,
    min_zoom: u8,
    max_zoom: u8,
    simplify: bool,
    tileset_name: &str,
    description: &str,
) -> Result<(Vec<u8>, String, VectorizeStats), AppError> {
    // ── Validation ────────────────────────────────────────────────────────────
    if layer_name.is_empty()
        || layer_name.len() > 64
        || !layer_name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        return Err(AppError::BadRequest(
            "layer_name must be 1–64 alphanumeric characters, hyphens, or underscores".into(),
        ));
    }
    if min_zoom > max_zoom {
        return Err(AppError::BadRequest(
            "min_zoom must be <= max_zoom".into(),
        ));
    }
    if max_zoom > 16 {
        return Err(AppError::BadRequest(
            "max_zoom > 16 is rarely useful and can produce very large files. Use max_zoom <= 16.".into(),
        ));
    }

    // ── Count features cheaply ────────────────────────────────────────────────
    let input_features: usize = {
        if let Ok(v) = serde_json::from_slice::<serde_json::Value>(file_bytes) {
            v.get("features")
                .and_then(|f| f.as_array())
                .map(|a| a.len())
                .unwrap_or(0)
        } else {
            0
        }
    };

    // ── Locate tippecanoe ────────────────────────────────────���────────────────
    let tippecanoe_path = locate_tippecanoe().await?;

    // ── Temp dir + write GeoJSON ──────────────────────────────────────────────
    let tmp_dir = tempfile::TempDir::new()
        .map_err(|e| AppError::Internal(anyhow::anyhow!("TempDir: {e}")))?;
    let geojson_path = tmp_dir.path().join("input.geojson");
    std::fs::write(&geojson_path, file_bytes)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("Write temp GeoJSON: {e}")))?;

    let out_path = tmp_dir.path().join("output.mbtiles");

    // ── Build command ─────────────────────────────────────────────────────────
    let effective_name = if tileset_name.is_empty() { layer_name } else { tileset_name };
    let effective_desc = if description.is_empty() {
        "Generated by MeridianRust".to_string()
    } else {
        description.to_string()
    };

    let mut cmd = tokio::process::Command::new(&tippecanoe_path);
    cmd.arg("--output").arg(&out_path)
        .arg("--layer").arg(layer_name)
        .arg("--minimum-zoom").arg(min_zoom.to_string())
        .arg("--maximum-zoom").arg(max_zoom.to_string())
        .arg("--name").arg(effective_name)
        .arg("--description").arg(&effective_desc)
        .arg("--force")
        .arg("--quiet");

    if simplify {
        cmd.arg("--drop-densest-as-needed")
           .arg("--extend-zooms-if-still-dropping");
    }

    cmd.arg(&geojson_path);

    // ── Run with timeout ──────────────────────────────────────────────────────
    let output = timeout(VECTORIZE_TIMEOUT, cmd.output())
        .await
        .map_err(|_| AppError::BadRequest(format!("tippecanoe timed out after {} seconds", VECTORIZE_TIMEOUT.as_secs())))?
        .map_err(|e| AppError::Internal(anyhow::anyhow!("tippecanoe spawn error: {e}")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let err = if !stderr.is_empty() { stderr } else { stdout };
        return Err(AppError::Internal(anyhow::anyhow!("tippecanoe failed: {err}")));
    }

    if !out_path.exists() {
        return Err(AppError::Internal(anyhow::anyhow!(
            "tippecanoe completed but output file was not created"
        )));
    }

    // ── Read output ───────────────────────────────────────────────────────────
    let mbtiles_bytes = std::fs::read(&out_path)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("Read mbtiles: {e}")))?;

    let size_bytes = mbtiles_bytes.len();
    let out_filename = format!("{layer_name}_z{min_zoom}-{max_zoom}.mbtiles");

    let stats = VectorizeStats {
        input_features,
        min_zoom,
        max_zoom,
        layer_name: layer_name.to_string(),
        size_bytes,
    };

    Ok((mbtiles_bytes, out_filename, stats))
}

// ── Helper: locate tippecanoe binary ─────────────────────────────────────────

async fn locate_tippecanoe() -> Result<String, AppError> {
    // Try `which` first
    let which_output = tokio::process::Command::new("which")
        .arg("tippecanoe")
        .output()
        .await;

    if let Ok(out) = which_output {
        if out.status.success() {
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if !path.is_empty() {
                return Ok(path);
            }
        }
    }

    // Fallback: common Homebrew locations
    for candidate in &["/opt/homebrew/bin/tippecanoe", "/usr/local/bin/tippecanoe"] {
        if std::path::Path::new(candidate).exists() {
            return Ok(candidate.to_string());
        }
    }

    Err(AppError::BadRequest(
        "tippecanoe is not installed or not in PATH. Install with: brew install tippecanoe".into(),
    ))
}
